name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTC: './rustc.sh'
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.67.0

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run tests
        run: make test
      - name: Run benchmarks
        run: make bench
      - name: Make docs
        run: cargo doc -p basic_dsp -p basic_dsp_vector -p basic_dsp_matrix --no-deps --no-default-features --features std,matrix
